version: "3.8"

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped